### ISSUE TITLE
Bundle broken

### ISSUE THREAD

**Issue by oglesbyanthony88** [learn-co-curriculum/rails-layouts-and-templates-lab#18]
```
learn open
Looking for lesson...
Forking lesson...
Cloning lesson...
Opening lesson...
Bundling...
Traceback (most recent call last):
	4: from /home/anthony/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
	3: from /home/anthony/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
	2: from /home/anthony/.rvm/gems/ruby-2.6.1/bin/bundle:23:in `<main>'
	1: from /home/anthony/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/rubygems.rb:294:in `activate_bin_path'
/home/anthony/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.0) required by your /home/anthony/code/labs/rails-layouts-and-templates-lab-online-web-ft-110419/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.0`
Done.
```
When `bundle -v` I get `Bundler version 2.1.4`

Fixed with `bundle update --bundler`

**Comment by lizbur10** [comment]
Hi there,

Raising issues on GitHub should be reserved for problems with the Learn.co curriculum, not environment or versioning problems.

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
